config/routes.rb
require 'sidekiq/web'

IpoWeb::Application.routes.draw do

  authenticated :login do
    root :to => "refinery/pages#home"
  end

  devise_for :logins, class_name: "Login"

  devise_scope :login do
    post 'logins/sign_up'  => "devise/registrations#create"
    get 'logins/sign_in' => 'devise/sessions#new'
    post 'logins/sign_in' => 'devise/sessions#create'
    get 'logins/sign_out' => 'devise/sessions#destroy'
    get 'logins/edit' => 'devise/registrations#edit', as: 'edit_login_registration'
    put 'logins/:id' => 'devise/registrations#update', as: 'login_registration'
  end

  resources :projects_setup, path: "/projects/setup", only: [:index, :show, :update, :edit]
  resources :projects do
    resources :project_media, as: 'media', path: 'media', only: [:create]
  end
  post '/projects/sync/:sf_object_id', to: 'projects#sync_with_sf'
  resources :project_media, only: [:show, :destroy]

  match '/home/autocomplete' => "home#autocomplete"
  match '/search' => 'home#wide_search', :as => :wide_search
  match '/autocomplete' => 'home#elastic_autocomplete'
  resources :students_setup, path: "/students/setup", only: [:index, :show, :update]
  get '/students_setup/project_sessions/:project' => 'students_setup#project_sessions'
  get '/projects_setup/application_deadline/:id' => 'projects_setup#application_deadline'

  resources :students
  post '/students/sync/:sf_object_id', to: 'students#sync_with_sf'
  post 'apply' => 'students#apply', :as => :apply

  resources :dashboards, only: [:index]
  resources :sessions
  get '/unique/:model/:attribute/:value' => 'uniqueness#validate', constraints: { value: /[^\/?]+/ }

  put "dashboards/update_login" => "dashboards#update_login"

  resources :organizations
  
  resources :donations, path: "/donations"
  get '/donate' => 'donations#new'
  get '/donate_to_student/:student_id' => 'donations#new', :as => :donate_to_student
  get '/renew_donation/:subscription_id' => 'donations#new', :as => :renew_donation
  get '/reserve_my_spot/:student_application_id' => 'donations#new', :as => :reserve_my_spot

  mount Sidekiq::Web, at: '/sidekiq'
  mount Refinery::Core::Engine, :at => '/'

  Refinery::Core::Engine.routes.draw do
    devise_scope :refinery_user do
      get "refinery/login", :to => "sessions#new", :as => :login
      get "refinery/logout", :to => "sessions#destroy", :as => :logout
      get "refinery/users/register" => 'users#new', :as => :new_signup
      post "refinery/users/register" => 'users#create', :as => :signup
    end

    devise_for :refinery_user, :class_name => 'Refinery::User',
               :path => "refinery/users",
               :controllers => { :registrations => 'refinery/users' },
               :skip => [:registrations],
               :path_names => { :sign_out => 'logout',
                                :sign_in => 'login',
                                :sign_up => 'register' }
  end
end

app/controllers/students_setup_controller.rb
class StudentsSetupController < ApplicationController
  before_filter :current_student_application, :clean_select_multiple_params
  include Wicked::Wizard
  steps :about_you, :interests_and_fields_of_study, :important_details, :confirmation


  def show
    @student_application.build_student unless @student_application.student
    case step
    when :about_you
      # This is used for the apply button in project/show.html.haml
      @project_selected = Project.find(params[:project_id]) if params[:project_id]
      build_default_associations(@student_application)
    when :interests_and_fields_of_study
      @academic_reference = PersonReference.find_or_build_person_reference(@student_application.person_references, :academic_reference)
      @spiritual_reference = PersonReference.find_or_build_person_reference(@student_application.person_references, :spiritual_reference)
      @new_academic_reference =  @student_application.person_references.build(reference_type: :academic_reference)
      @new_spiritual_reference = @student_application.person_references.build(reference_type: :spiritual_reference)
    end
    @student_application.wizard_status = step.to_s
    render_wizard
  end

  def update
    case step
    when :interests_and_fields_of_study
      remove_extra_attributes("spiritual_reference", params[:is_new_spiritual_reference])
      remove_extra_attributes("academic_reference", params[:is_new_academic_reference])
    end

    params[:student_application][:wizard_status] = step.to_s
    if step == :important_details
      params[:student_application][:wizard_status] = 'complete'
      @student_application.set_to_complete
    end

    if @student_application.update_attributes params[:student_application]            
      # create/update SF object
      StudentApplicationSyncWorker.perform_async(@student_application.id) if step == :important_details
      create_login_session unless login_signed_in?
    elsif step == :about_you
      build_default_associations(@student_application)
    end

    render_wizard @student_application
    session[:student_application] = @student_application.id    
  end

  def project_sessions
    selected_session = @student_application.project_session || @student_application.build_project_session
    @projects_sessions = ProjectSession.where(project_id: params[:project])
    @projects_sessions.select! { |p| p.seats_left? } # Only show project sessions that aren't full.
    @projects_sessions.map! { |session| {
      id: session.id, text: session.select_label, 
      selected: session.id == selected_session.id }}
    respond_to do |format|
      format.json { render :json => @projects_sessions }
    end
  end

  private

  def build_default_associations(student_application)
    student_application.student.build_login unless student_application.student && student_application.student.login
    student_application.build_project_session unless student_application.project_session
    student_application.project_session.build_project unless student_application.project    
  end


  def person_references_params
    student_params[:person_references_attributes]
  end

  def student_params
    params[:student_application][:student_attributes]
  end

  def current_student_application
    @student_application ||= begin
      student_application = session[:student_application] && StudentApplication.find(session[:student_application])
      student_application ||= associate_to_student
    end
  end

  def associate_to_student
    return StudentApplication.new unless current_student
    StudentApplication.new(student_id: current_student.id)
  end

  def create_login_session
    sign_in @student_application.student.login
  end

  def clean_select_multiple_params hash = params
    hash.each do |k, v|
      case v
      when Array then v.reject!(&:blank?)
      when Hash then clean_select_multiple_params(v)
      end
    end
  end

  def remove_extra_attributes(reference, value)
    if value == "true"
      person_references_params.reject! { |k, v| !v['reference_id'].nil? && v['reference_type'] == reference }
    else
      person_references_params.reject! { |k, v| v['reference_id'].blank? && v['reference_type'] == reference }
    end
  end
end

app/helpers/students_setup_helper.rb
module StudentsSetupHelper
end

app/views/students_setup/_header.html.haml
.new-student-header
  %h1.center= t(:student_setup_application)
  - step_index = wizard_steps.index(step) + 1
  .wizard-steps
    .wizard-bar
      .fill{class: "step#{step_index}"}

    %ul
      = wizard_step t(:about_you), 1, students_setup_path(:about_you), step_index
      = wizard_step t(:interests_and_fields_of_study), 2, students_setup_path(:interests_and_fields_of_study), step_index
      = wizard_step t(:important_details), 3, students_setup_path(:important_details), step_index
      = wizard_step t(:confirmation), 4, students_setup_path(:confirmation), step_index

app/views/students_setup/_header.html.slim
.new-student-header
  h1.center Student Setup Application
  - step_index = wizard_steps.index(step) + 1
  .wizard-steps
    .wizard-bar
      .fill class= "step#{step_index}"

    ul
      = wizard_step "About You"                    , 1, students_setup_path(:about_you), step_index
      = wizard_step "Interests and Fields of Study", 2, students_setup_path(:interests_and_fields_of_study), step_index
      = wizard_step "Important Details"            , 3, students_setup_path(:important_details), step_index
      = wizard_step "Confirmation"                 , 4, students_setup_path(:confirmation), step_index

app/views/students_setup/_reference.html.haml
= hidden_field_tag "is_new_#{type}", false
%ul.tab-list.small
  %li.tab.active(id= "tab_existing_#{type}" data-box="#existing_#{type}")
    %a(href="##{type}")= t(:choose_existing)
  %li.tab(id= "tab_new_#{type}" data-box="#new_#{type}")
    %a(href='##{type}')= t(:new_reference)
%div.tab-box.w-padding{id: "existing_#{type}"}
  = f_student.fields_for :person_references, person_reference do |reference|
    = reference.association :reference, include_blank: true, label: t(:select_reference), label_method: :select_label
    = reference.input :reference_type, as: :hidden, input_html: { value: type.to_sym }
  %p= t(:if_you_cant_find_your_reference)
%div.tab-box.w-padding{id: "new_#{type}", style: "display: none"}
  .student_fields 
    = f_student.fields_for :person_references, new_person_reference, validate: true do |f_s|
      = f_s.input :contact_first_name
      = f_s.input :contact_last_name
      = f_s.input :contact_email, label: t(:email_address)
      = f_s.input :contact_phone
      = f_s.input :contact_description, label: t(:how_do_you_know_this_person)
      = f_s.input :reference_type, as: :hidden, input_html: { value: type.to_sym }

app/views/students_setup/_student_app_detail.html.haml
.tile
  .first-column
    %label=@student_application.project_session.project.name

  .second-column
    %label= @student_application.project_session.select_label

app/views/students_setup/about_you.html.haml
%article.container
  = render 'header', active_step: params[:id]

  = simple_form_for @student_application, url: wizard_path, method: :put, html: {id: "new_student"} do |f|
    = render partial: 'shared/errors', locals: {object: @student_application}

    .background.c12.omega
      - if @project_selected
        %h3.center= "#{t(:your_project)} #{@project_selected.name}"
        = f.input :id, as: :hidden, input_html: { id: 'your_project_select', value: @project_selected.id }
      - else
        %h3.center= t(:your_project)
        = f.input :project, as: :select, label: false do
          = select_tag 'your_project_select', options_from_collection_for_select(Project.available_seats, "id", "name", @student_application.project_id), include_blank: true
          
      %h3.center= t(:your_session)
      - # collection is loaded dynamically from server.
      = f.association :project_session, collection: [], include_blank: true, label: false, label_method: :select_label

    = f.fields_for :student, @student_application.student, validate: true do |f_student|
      %fieldset
        %br
        .student-fields
          = f_student.input :first_name, label: t(:first_name_nickname)
          = f_student.input :last_name
          - unless current_student
            = f_student.fields_for :login, @student_application.student_login, validate: true do |f_login|
              = f_login.input :email
              = f_login.input :password
              - # Out of place. Find better place for this
              - # %p.register-description= t(:we_setup_an_account_for_you_so_you_can_check_your_application_status)
              = f_login.input :password_confirmation, label: t(:confirm_password)
              = f_student.input :marital_status, as: :select

          = f_student.input :birthday, as: :date, start_year: Date.today.year - 50, label: t(:date_of_birth), order: [:year, :month, :day]
          = f_student.input :gender, collection: [:female, :male], as: :radio_buttons, input_html: {data: { toggle: "radio"}}
          

      %fieldset
        .student-fields
          = f_student.input :street_address
          = f_student.input :city
          = f_student.input :state
          = f_student.input :postal_code
          = f_student.input :country

          = f_student.input :preferred_phone
          = f_student.input :phone_type

          = f_student.input :organization, label: t(:school_church_organization)

      %fieldset
        %h4= t(:how_did_your_hear_about_ipo_connection)
        = f_student.input :heard_about_ipo, as: :check_boxes, label: false, input_html: { data: { toggle: "checkbox" }}

      %fieldset
        %h4= t(:had_you_event_applied_to_an_ipo_connection_program_before)
        = f_student.input :applied_ipo_before, as: :radio_buttons, label: false, required: true, input_html: { data: { toggle: "radio"}}

    = f.submit t(:save_and_continue_to_step_2), class: "button button-orange"

app/views/students_setup/about_you.html.slim
.container
  = render 'header', active_step: params[:id]

  = simple_form_for @student, url: wizard_path, method: :put, validate: true, html: {id: "new_student"} do |f|
    = render partial: 'shared/errors', locals: {object: @student}

    .background.c12.omega
      h3.center Your Project:
      = f.association :project, include_blank: true, label: false

      h3.center Your Session:
      = f.association :project_session, include_blank: true, label: false, label_method: :select_label


    fieldset
      .student-fields
        = f.input :first_name, label: "First Name (Nickname)"
        = f.input :last_name

        = f.input :email
        = f.input :password
        p.register-description We'll setup an account for you so you can check your application status, update your info, access important material and setup a funraising page!
        = f.input :password_confirmation, label: "Confirm Password"

        = f.input :birthday, start_year: (Date.today - 50.years).year, label: "Date of Birth"
        = f.input :gender, collection: [:female, :male], as: :radio_buttons
        = f.input :marital_status, as: :select

    fieldset
      .student-fields
        = f.input :street_address
        = f.input :city
        = f.input :postal_code
        = f.input :country

        = f.input :preferred_phone
        = f.input :phone_type

        = f.input :organization, label: "School, Church, Student Organization"

        = f.input :experiences, as: :select, label: "Please list your cross-cultural experiences"
        p.experiences-description
          i.fa.fa-globe Cross-Cultural Experience Requirement
          br
          | The IPO Connection internship is designed to extend and further your cross-cultural experiences. We require applying students to have at least one cross-cultural experience. If you yet have a cross-cultural experience, we encourage you to find an opportunity before applying.

    fieldset
      h4 How did you hear about the IPO Connection?
      = f.input :heard_about_ipo, as: :check_boxes, label: false

    fieldset
      h4 Had you ever applied to an IPO Connection program before?
      = f.input :applied_ipo_before, as: :radio_buttons, label: false

    = f.submit "Save & Continue to Step #2", class: "button button-orange"

app/views/students_setup/confirmation.html.haml
.container
  = render 'header', active_step: params[:id]

  .confirmation

    %h2= t(:app_confirmation)
    %p= t(:student_app_conf_detail)

    .c6
      %label= t(:name)
      %p=@student_application.student.full_name

    .c6.omega
      %label= t(:confirmation_has_been_mail_to)
      %p=@student_application.student.login.email

    .c6
      %label= t(:desired_project)
      %p=@student_application.project_session.project.name

    .c6.omega
      %label= t(:session)
      %p=@student_application.project_session.select_label

    .c6
      %label= t(:your_address)
      %p=@student_application.student.full_address

    .clearfix

  .c12
    %strong= t(:what_do_i_expect_next)
    %ul
      %li= t(:youll_get_this_confirmation_in_your_email)
      %li= t(:student_references)
      %li= t(:weve_signed_you_up_for_your_enewsletter)
      %li= t(:we_review_your_application_in_3_business_days)
    .spacer
    %p= t(:talk_soon_ipo_support_staff)

app/views/students_setup/confirmation.html.slim
.container
  = render 'header', active_step: params[:id]

  .info-box
    .first-column
      h8 Desired Project
      p=@student.project.name

    .second-column
      h8 Start Date
      p=@student.project_session.select_label

    .clearfix

  .confirmation
    .hr
    h2.center App Confirmation

    .first-column
      h8 Name
      p=@student.full_name

    .second-column
      h8 Confirmation has been mailed to
      p=@student.customer.email

    .first-column
      h8 Desired Project
      p=@student.project.name

    .second-column
      h8 Session
      p=@student.project_session.select_label

    .first-column
      h8 Your Address
      p=@student.full_address

    .clearfix
    .spacer
    .hr

  .what_expect
    strong What do I expect next?
    ul
      li You'll get this confirmation in your email, so no need to print.
      li We've signed you up for our eNewsletter (unsubscribe any time)
      li Prepare your passport and read our <a href="#">I've applied, what are my next steps blog post</a>
      li We'll review your application in 3 business days and send an email with your status. If we need anything, we'll email or call you up.
 
    strong Talk soon! ~ IPO Support Staff*

app/views/students_setup/important_details.html.haml
.container
  = render 'header', active_step: params[:id]
  = render 'student_app_detail'

  .important-details
    %h2= t(:important_note)
    %p= t(:after_initial_acceptance_addictional_information_will_be_required)

    %h2= t(:whats_next)

    %p= t(:once_accepted_we_will_send_a_supplemental_information)
   
    %p
      %label= t(:suplemental_information_form)
      %br= t(:when_your_application_file_is_complete)
    %p
      %label= t(:tuition)
      %br= t(:the_tuition_fees_varies_according_to_our_international_fee_scale)
    %p
      = t(:the_ipo_course_tuition_does_not_include_field_fees)
    %p
      %label= t(:field_fees)
      %br= t(:field_fees_include_housing_food_and_local_travel) 
    %p
      %label= t(:travel_expenses_and_personal_spendings)
      %br= t(:the_ipo_tuition_and_field_fees_do_not_include_tral_expenses)
    %p
      %label= t(:making_the_ipo_connection)
      %br= t(:the_field_project_host_has_agreed_to_arrange_for_your_arrival_pick_up)

    %h2= t(:terms_and_conditions)

    .terms-and-conditions
      %p= t(:these_would_be_the_terms_and_conditions_including_privacy_information)

    = simple_form_for @student_application, url: wizard_path, method: :put do |f|

      = f.input :agree_terms, as: :boolean, label: t(:i_agree_to_the_terms_and_conditions), input_html: { data: { toggle: "checkbox" }}

      = f.submit t(:save_and_finish), class: "button button-orange"

    .clearfix

app/views/students_setup/important_details.html.slim
.container
  = render 'header', active_step: params[:id]

  .info-box
    .first-column
      h8 Desired Project
      p=@student.project.name

    .second-column
      h8 Start Date
      p=@student.project_session.select_label

    .clearfix

  .important-details
    h2
      i.fa.fa-exclamation-triangle
      | Important Note
    p After initial acceptance, additional information will be required, including passport, insurance (with offer to purchase a travel insurance policy), etc.

    h2
      i.fa.fa-hand-o-right
      | What's Next!

    p Once accepted, we will send a Supplemental Information Form with instructions for participation, including fund raising, insurance, and the IPO online course. 
   
    p
      strong
        | *Supplemental Information Form*
      br
      | When your application file is complete, the Field Host will confirm your acceptance. Then your IPO Mentor will enroll you in the IPO Course online. The IPO Course has nine pre-departure lessons comprised of fifty short video interviews.
    p
      strong
        | *Tuition*
      br
      | The Tuition fee varies according to our International Fee Scale (World A, B, and C - Most Developed to Least Developed), which is determined by your nation of citizenship. World A tuition is $400 USD; World B is $100 USD; and World C is $10 USD. To find out the fee scale for your country of citizenship, please see the International Fee Scale. 
    p
      The IPO Course Tuition does not include Field Fees, Travel Expenses or Personal Spending Money. 
    p
      strong
        | *Field Fees*
      br
      | Field Fees include housing, food, and local travel expenses and they vary according to the length of stay and location of the Project. 
    p
      strong
        | *Travel Expenses & Personal Spending*
      br
      | The IPO Tuition and Field Fees do not include travel expenses to and from your home, passport and visa fees, and/or personal travel and personal items. 
    p
      strong
        | *Making the IPO Connection*
      br
      | The Field Project Host has agreed to arrange for your arrival pick up and daily oversight during your internship stay. Your Host has also agreed to help you get acquainted with the culture, the community, and the project personnel. Please understand, you will be expected to abide by the community-corporate culture guidelines as outlined by the Host. 

    h2 Terms and Conditions

    .terms-and-conditions
      p These would be the terms and conditions including privacy information...

    = simple_form_for @student, url: wizard_path, method: :put, validate: true do |f|
      = f.input :agree_terms, as: :boolean, label: "I agree to the Terms and Conditions"

      = f.submit "Save & Finish!", class: "button button-orange"

    .clearfix

app/views/students_setup/interests_and_fields_of_study.html.haml
.container
  = render 'header', active_step: params[:id]
  = render 'student_app_detail'

  = simple_form_for @student_application, url: wizard_path, method: :put, validate: true do |f|

    = f.fields_for :student, @student_application.student, validate: true do |f_student| 
      %fieldset
        .student-fields
          = f_student.input :passions, as: :select, label: t(:what_are_your_passions)

          = f_student.input :overall_education, as: :select, label: t(:highest_education_completed)
          = f_student.input :graduation_year, collection: ((Date.today.year - 50)..(Date.today.year)).to_a.reverse

          = f_student.input :spoken_languages, as: :select
          = f_student.input :fields_of_study, as: :select

          = f_student.input :experiences, as: :select, label: t(:please_list_your_cross_cultural_experiences)
          %p.experiences-description
            %i.fa.fa-globe= t(:cross_cultural_experience_requirement)
            %br
            = t(:the_ipo_connection_internship_is_designed_to_extend_and_further)

          = f_student.input :description, label: t(:tell_us_about_yourself)

      %fieldset#spiritual_reference
        %h2= t(:spiritual_reference)
        %p= t(:we_require_one_spiritual_reference)
        = render partial: "reference", locals: { f_student: f_student, person_reference: @spiritual_reference, new_person_reference: @new_spiritual_reference, type: "spiritual_reference" }
  
      %fieldset#academic_reference
        %h2= t(:academic_reference)
        %p= t(:we_require_one_academic_reference)
        = render partial: "reference", locals: { f_student: f_student, person_reference: @academic_reference, new_person_reference: @new_academic_reference, type: "academic_reference" }

    = f.submit t(:save_and_continue_to_step_3), class: "button button-orange"

app/views/students_setup/interests_and_fields_of_study.html.slim
.container
  = render 'header', active_step: params[:id]

  .info-box
    .first-column
      h8 Desired Project
      p=@student.project.name

    .second-column
      h8 Start Date
      p=@student.project_session.select_label

    .clearfix

  = simple_form_for @student, url: wizard_path, method: :put, validate: true do |f|
    fieldset
      .student-fields
        = f.input :passions, as: :select, label: "What are your passions?"

        = f.input :overall_education, as: :select, label: "Highest education completed"
        = f.input :graduation_year, collection: ((Date.today.year - 50)..(Date.today.year)).to_a.reverse

        = f.input :spoken_languages, as: :select
        = f.input :fields_of_study, as: :select

        = f.input :description, label: "Tell us about yourself..."

    fieldset.reference
      h2 Spiritual Reference
      p
        | *We require one spiritual reference (pastor, campus leader, etc.). We will send them an email when you complete this application to verify their contact information and setup a quick call with an IPO Staff member.*
      .student_fields     
        = f.fields_for :spiritual_reference, @student.spiritual_reference, validate: true do |f_r|
          = f_r.input :first_name
          = f_r.input :last_name
          = f_r.input :email, label: "Email address"
          = f_r.input :phone

          = f_r.input :description, label: "How do you know this person?"

    fieldset.reference
      h2 Academic Reference
      p
        | *We one academic reference (professor/teacher, academic advisor, etc.). We will send them an email when you complete this application to verify their contact information and setup a quick call with an IPO Staff member.*
      .student_fields     
        = f.fields_for :academic_reference, @student.academic_reference, validate: true do |f_r|
          = f_r.input :first_name
          = f_r.input :last_name
          = f_r.input :email, label: "Email address"
          = f_r.input :phone

          = f_r.input :description, label: "How do you know this person?"

    = f.submit "Save & Continue to Step #3", class: "button button-orange"