config/routes.rb
require 'sidekiq/web'

IpoWeb::Application.routes.draw do

  authenticated :login do
    root :to => "refinery/pages#home"
  end

  devise_for :logins, class_name: "Login"

  devise_scope :login do
    post 'logins/sign_up'  => "devise/registrations#create"
    get 'logins/sign_in' => 'devise/sessions#new'
    post 'logins/sign_in' => 'devise/sessions#create'
    get 'logins/sign_out' => 'devise/sessions#destroy'
    get 'logins/edit' => 'devise/registrations#edit', as: 'edit_login_registration'
    put 'logins/:id' => 'devise/registrations#update', as: 'login_registration'
  end

  resources :projects_setup, path: "/projects/setup", only: [:index, :show, :update, :edit]
  resources :projects do
    resources :project_media, as: 'media', path: 'media', only: [:create]
  end
  post '/projects/sync/:sf_object_id', to: 'projects#sync_with_sf'
  resources :project_media, only: [:show, :destroy]

  match '/home/autocomplete' => "home#autocomplete"
  match '/search' => 'home#wide_search', :as => :wide_search
  match '/autocomplete' => 'home#elastic_autocomplete'
  resources :students_setup, path: "/students/setup", only: [:index, :show, :update]
  get '/students_setup/project_sessions/:project' => 'students_setup#project_sessions'
  get '/projects_setup/application_deadline/:id' => 'projects_setup#application_deadline'

  resources :students
  post '/students/sync/:sf_object_id', to: 'students#sync_with_sf'
  post 'apply' => 'students#apply', :as => :apply

  resources :dashboards, only: [:index]
  resources :sessions
  get '/unique/:model/:attribute/:value' => 'uniqueness#validate', constraints: { value: /[^\/?]+/ }

  put "dashboards/update_login" => "dashboards#update_login"

  resources :organizations
  
  resources :donations, path: "/donations"
  get '/donate' => 'donations#new'
  get '/donate_to_student/:student_id' => 'donations#new', :as => :donate_to_student
  get '/renew_donation/:subscription_id' => 'donations#new', :as => :renew_donation
  get '/reserve_my_spot/:student_application_id' => 'donations#new', :as => :reserve_my_spot

  mount Sidekiq::Web, at: '/sidekiq'
  mount Refinery::Core::Engine, :at => '/'

  Refinery::Core::Engine.routes.draw do
    devise_scope :refinery_user do
      get "refinery/login", :to => "sessions#new", :as => :login
      get "refinery/logout", :to => "sessions#destroy", :as => :logout
      get "refinery/users/register" => 'users#new', :as => :new_signup
      post "refinery/users/register" => 'users#create', :as => :signup
    end

    devise_for :refinery_user, :class_name => 'Refinery::User',
               :path => "refinery/users",
               :controllers => { :registrations => 'refinery/users' },
               :skip => [:registrations],
               :path_names => { :sign_out => 'logout',
                                :sign_in => 'login',
                                :sign_up => 'register' }
  end
end

app/views/shared/_errors.html.haml
- if object.errors.any?
  %h4= "#{pluralize(object.errors.count, "error", "errors")} prohibited that the register was saved:"
  %br
  %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_errors.html.slim
- if object.errors.any?
  h4= "#{pluralize(object.errors.count, "error", "errors")} prohibited that the register was saved:"
  br
  ul
    - object.errors.full_messages.each do |msg|
      li= msg

app/views/shared/_footer.html.haml
%footer.box.box-grey.light-text
  .container
    .c6
      .footer-col
        %h3 explore
        = footer_menu('explore').to_html

      .footer-col
        %h3 about converge
        = footer_menu('about').to_html

      .footer-col
        %h3 resources
        = footer_menu('resources').to_html    

      #footer-logo.c12.omega= image_tag "ywam_initiative.png"      

    #reach-out.c6.omega
      = simple_form_for :apply, url: '/apply', method: 'post', remote: true do |f|
        %h1 reach out
        %div
          %span Hi, my name is
          = f.input :first_name, label: false, placeholder: 'First Name', required: true
          = f.input :last_name, label: false, placeholder: 'Last Name', required: true
          = f.input :email, label: false, placeholder: 'Enter email address...'
          %span I'm interested in...
          = f.input :interest_in, label: false, collection: ['Hosting Interns', 'Internship or Outreach', 'Joining Staff Team', 'Mentoring Students', 'Supporting this Ministry', 'Request a Speaker', 'Other']
        %div

        = f.submit "Go!", :disable_with => "Submitting...", class: "button"

app/views/shared/_footer.html.slim
footer.box.box-grey
  .container
    .c6
      .footer-col
        h3 explore
        ul
          li global internships
          li our blog
          li events & webinars
          li facebook
          li twitter
          li youtube

      .footer-col
        h3 about ipo
        ul
          li who we are
          li how IPO works
          li partner organizations
          li financial information

      .footer-col
        h3 resources
        ul
          li Finding the right internship
          li setting up a project
          li becoming a mentor
          li fundraising toolkit
          li for parents
          li insurance information
          li travel alert
          li academic credit 4

    #reach-out.c6.omega
      h1 reach out
      div
        span Hi, my name is
        input type='text' placeholder='Enter Full Name' name='full_name'

      div
        select
          option I'm interested in an internship
        span . Please
        select
          option Email me

      div
        span using...
        input type='email' placeholder='Enter email address...' name='email'

app/views/shared/_head.html.haml
%head
  %meta{:name => "viewport", :content => "width=device-width; initial-scale=1.0; maximum-scale=1.0;"}
  %title= t(:website_title)
  = stylesheet_link_tag "application", media: "all"
  <link href='//fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
  = javascript_include_tag "application"
  = csrf_meta_tags

app/views/shared/_head.html.slim
head
  title ipo web
  = stylesheet_link_tag    "application", media: "all"
  link href='http://fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'
  link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'
  = javascript_include_tag "application"
  = csrf_meta_tags

app/views/shared/_main_nav_links.html.haml
.main_nav_links
  - menu_pages.each do |page|
    %li= link_to page.menu_title, page.slug

app/views/shared/_media_progress.html.haml
%script#template-upload(type="text/x-impl")
  .upload
    {%=o.name%}
    .progress
      .bar(style="width: 0%")

app/views/shared/_navigation.html.haml
%nav.main
  = NavigationMenu.new(refinery_menu_pages, self).to_html
  
  %span
  = form_tag '/search', :method => :get do
    = search_field_tag :search, @search, :autocomplete => false, :value => "Search + Enter".html_safe
    = submit_tag 'Search', :class => 'button button-green', :id => 'submit' 

  = yield :navigation

app/views/shared/_navigation.html.slim
nav
  span.link.heading internships
  span.link.heading about ipo
  span.link.heading stories
  -if current_customer
    span.link.heading=link_to "log out", logout_path
  -else
    span.link.heading=link_to "log in", login_path

app/views/shared/_secondary_navigation.html.haml
- # Main navigation.
.secondary-header
  %nav.container= render 'shared/secondary_navigation_links'

app/views/shared/_secondary_navigation_links.html.haml
.secondary_nav_links
  - unless current_login && current_login.student?
    -# %span.link.heading
    %li
      = link_to main_app.projects_setup_index_path do
        %span.entypo-submit
        submit a project

  - unless current_login && current_login.field_host?
    %li
      = link_to main_app.students_setup_index_path do
        %span.entypo-apply
        apply

  - if current_login
    %li
      = link_to main_app.new_donation_path do
        %span.entypo-donate
        donate

    %li
      = link_to main_app.dashboards_path do
        %span.entypo-dashboard
          your dashboard

    %li
      = link_to main_app.destroy_login_session_path do
        %span.entypo-logout
        log out
  - else
    %li
      = link_to main_app.new_donation_path do
        %span.entypo-donate
        donate

    %li
      = link_to main_app.new_login_session_path do
        %span.entypo-login
        log in

app/views/shared/_side_nav.html.haml
- # Mobile navigation.
.side-nav
  - # Placeholder nav.main for responsive hamburger.
  %nav.main
  = form_tag '/search', :method => :get do
    = search_field_tag :search, @search, :autocomplete => false, :value => "Search + Enter".html_safe
    = submit_tag 'Search', :class => 'button button-green', :id => 'submit' 
  = render 'shared/secondary_navigation_links'
  = render 'shared/main_nav_links'

app/views/shared/_sub_menus.html.haml
- if page
  = NavigationMenu.new(refinery_menu_pages, self).render_submenu