config/routes.rb
require 'sidekiq/web'

IpoWeb::Application.routes.draw do

  authenticated :login do
    root :to => "refinery/pages#home"
  end

  devise_for :logins, class_name: "Login"

  devise_scope :login do
    post 'logins/sign_up'  => "devise/registrations#create"
    get 'logins/sign_in' => 'devise/sessions#new'
    post 'logins/sign_in' => 'devise/sessions#create'
    get 'logins/sign_out' => 'devise/sessions#destroy'
    get 'logins/edit' => 'devise/registrations#edit', as: 'edit_login_registration'
    put 'logins/:id' => 'devise/registrations#update', as: 'login_registration'
  end

  resources :projects_setup, path: "/projects/setup", only: [:index, :show, :update, :edit]
  resources :projects do
    resources :project_media, as: 'media', path: 'media', only: [:create]
  end
  post '/projects/sync/:sf_object_id', to: 'projects#sync_with_sf'
  resources :project_media, only: [:show, :destroy]

  match '/home/autocomplete' => "home#autocomplete"
  match '/search' => 'home#wide_search', :as => :wide_search
  match '/autocomplete' => 'home#elastic_autocomplete'
  resources :students_setup, path: "/students/setup", only: [:index, :show, :update]
  get '/students_setup/project_sessions/:project' => 'students_setup#project_sessions'
  get '/projects_setup/application_deadline/:id' => 'projects_setup#application_deadline'

  resources :students
  post '/students/sync/:sf_object_id', to: 'students#sync_with_sf'
  post 'apply' => 'students#apply', :as => :apply

  resources :dashboards, only: [:index]
  resources :sessions
  get '/unique/:model/:attribute/:value' => 'uniqueness#validate', constraints: { value: /[^\/?]+/ }

  put "dashboards/update_login" => "dashboards#update_login"

  resources :organizations
  
  resources :donations, path: "/donations"
  get '/donate' => 'donations#new'
  get '/donate_to_student/:student_id' => 'donations#new', :as => :donate_to_student
  get '/renew_donation/:subscription_id' => 'donations#new', :as => :renew_donation
  get '/reserve_my_spot/:student_application_id' => 'donations#new', :as => :reserve_my_spot

  mount Sidekiq::Web, at: '/sidekiq'
  mount Refinery::Core::Engine, :at => '/'

  Refinery::Core::Engine.routes.draw do
    devise_scope :refinery_user do
      get "refinery/login", :to => "sessions#new", :as => :login
      get "refinery/logout", :to => "sessions#destroy", :as => :logout
      get "refinery/users/register" => 'users#new', :as => :new_signup
      post "refinery/users/register" => 'users#create', :as => :signup
    end

    devise_for :refinery_user, :class_name => 'Refinery::User',
               :path => "refinery/users",
               :controllers => { :registrations => 'refinery/users' },
               :skip => [:registrations],
               :path_names => { :sign_out => 'logout',
                                :sign_in => 'login',
                                :sign_up => 'register' }
  end
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  ACTIVE = "Active"
  SUBMITTED = "Submitted"
  CANCELED = "Canceled"

  SPOT_PRICE = 25

  attr_accessible :amount, :customer_id, :subscription_id, :transcation_id, :recurring, :status, :student_id

  belongs_to :student
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :create_donation_processor

  def show
    @subscription = @donation_processor.get_subscription(params[:id])
    donation = Donation.find_by_subscription_id(@subscription.id)
    @student = Student.find(donation.student_id) if donation && donation.student_id
  end

  def new
    define_amounts
    if params[:subscription_id].present?  #renew existing donation
      @subscription = @donation_processor.get_subscription(params[:subscription_id])
      @customer = @donation_processor.get_customer(params[:subscription_id])
    elsif params[:student_id].present?  #donation for a specific student
      @student = Student.find(params[:student_id])
    elsif params[:student_application_id].present? #donation to reserve an spot
      @student = current_student if current_student
      @student_application_id = params[:student_application_id]
      flash.now[:notice] = 'Reserve My Spot for $25!'
      render action: "new"
    end
    #else donation for the whole project no action needed
  end

  def create
    result = @donation_processor.process_donation
    if result.success? 
      if @donation_processor.spot_reservation?

        # TODO: Refactor this code to somewhere else.
        student_application = StudentApplication.find(params[:donation][:student_application_id])
        student_application.set_to_reserved!
        StudentApplicationSyncWorker.perform_async(student_application.id) # Push change to salesforce.

        redirect_to dashboards_path(view: 'profile_page') and return 
      end
      flash.now[:notice] = 'Thanks for your donation!'
      render action: "show"
    else
      define_amounts unless @donation_processor.spot_reservation?
      flash[:error] = "Error: #{result.message}"
      render action: "new"
    end
  end

  def destroy
    subscription = @donation_processor.cancel_recurring_donation(params[:id])
    Donation.find_by_subscription_id(subscription.id).update_attribute(:status, Donation::CANCELED)
    flash.now[:notice] = 'Your recurring donation has been canceled!'
    redirect_to action: "show", id: subscription.id
  end

  private

  def define_amounts
    @amounts = [
      ["$10", "10"],
      ["$35","35"],
      ["$50","50"],
      ["$100","100"],
      ["$250","250"],
      ["$500","500"]
    ]
    @amounts = nil if params[:student_application_id].present?
  end

  def create_donation_processor 
    @donation_processor = DonationProcessor.new(params)
  end

end

app/views/donations/new.html.haml
%article.container
  %h1= t(:donation_support_ipo_connection) 
  %p= t(:donation_contribution_description)

  - if flash[:error]
    %p.alert= flash[:error]
  - if @student
    %p= "#{t(:donation_for)} #{@student.full_name}"
  = simple_form_for :donation, url: donations_path, html: { id: 'donate_form', novalidate: false } do |f|
    = f.input :student_id, as: :hidden, input_html: { value: (@student.id if @student) }
    -if @amounts
      = f.input :amount, as: :button_group, label: false, collection: @amounts, validate: true
      = number_field_tag :custom_amount, (@subscription.price if @subscription), min: 1, placeholder: '$ other amount'
    -else 
      .input.c6
        %h3= t(:donation_for_reserve_my_spot)
        = f.input :student_application_id, as: :hidden, input_html: { value: (@student_application_id if @student_application_id) }

    .input.c6
      %label= t(:donation_first_name)
      = text_field_tag 'customer[first_name]', (@customer.first_name if @customer), required: true
    .input.c6.omega
      %label= t(:donation_last_name)
      = text_field_tag 'customer[last_name]', (@customer.last_name if @customer), required: true
    .input.c12.omega
      %label= t(:donation_email)
      = email_field_tag 'customer[email]', (@customer.email if @customer), required: true
    .input.c8
      %label= t(:donation_address)
      = text_field_tag 'billing[street_address]', '', required: true
    .input.c4.omega
      %label= t(:donation_postal_code)
      = text_field_tag 'billing[postal_code]', '', required: true

    .security-container.c12.omega
      .input.c7
        %label= t(:donation_phone)
        = phone_field_tag 'customer[phone]', '', required: true

      .security.box.c5
        %h3= t(:donation_security)
        %p= t(:donation_secure_transaction)
        %p= t(:donation_secure_transaction_description)

    .input.c4
      %label= t(:donation_card_number)
      = text_field_tag :number,'', autocomplete: "off", name: "", "data-encrypted-name" => "card[number]", value: "", required: true

    .input.c3
      %label= t(:donation_cvv)
      = text_field_tag :number,'', autocomplete: "off", name: "", "data-encrypted-name" => "card[cvv]", value: "", required: true

    .input.c12
      %label= t(:donation_expiration_date)
      = select_month(Date.today, field_name: "expiration_month", add_month_numbers: true, prefix: "card")
      = select_year(Date.today, field_name: "expiration_year", start_year: 2014, prefix: "card")

    .input.c12.omega{style: 'margin-top: 50px;'}
      -if @amounts
        = f.input :recurring, label: t(:recurring), as: :boolean, :input_html => {:data => {:toggle => "checkbox"}}
      = submit_tag t(:donation_button), class: 'button button-orange'


:plain
  <script type="text/javascript" src="https://js.braintreegateway.com/v1/braintree.js"></script>

:javascript
  var braintree = Braintree.create("#{BRAINTREE_CONFIG[:client_side_encryption_key]}");
  braintree.onSubmitEncryptForm('donate_form');
  connect_group_to_select($(".donation_amount.button_group"), $("#donation_amount"),function(select) { select.valid() })

app/views/donations/show.html.haml
.container
  %h1= flash[:notice] || t(:donation_title)
  - if @subscription
    #donations
      %table.table
        %thead.table-head
          %th= t(:donation_code)
          %th= t(:donation_price)
          %th= t(:donation_status)
          %th
        %tbody.table-body
          %tr
            %td= @subscription.id
            %td= @subscription.price
            %td= @subscription.status
            -if @subscription.status == "Canceled"
              -if @student
                %td= link_to t(:donation_renew), donate_to_student_path(student_id: @student.id)
              -else
                %td= link_to t(:donation_renew), renew_donation_path(subscription_id: @subscription.id)
            -else
              %td= link_to t(:donation_cancel), donation_path(@subscription.id), confirm: t(:are_you_sure), method: :delete