config/routes.rb
require 'sidekiq/web'

IpoWeb::Application.routes.draw do

  authenticated :login do
    root :to => "refinery/pages#home"
  end

  devise_for :logins, class_name: "Login"

  devise_scope :login do
    post 'logins/sign_up'  => "devise/registrations#create"
    get 'logins/sign_in' => 'devise/sessions#new'
    post 'logins/sign_in' => 'devise/sessions#create'
    get 'logins/sign_out' => 'devise/sessions#destroy'
    get 'logins/edit' => 'devise/registrations#edit', as: 'edit_login_registration'
    put 'logins/:id' => 'devise/registrations#update', as: 'login_registration'
  end

  resources :projects_setup, path: "/projects/setup", only: [:index, :show, :update, :edit]
  resources :projects do
    resources :project_media, as: 'media', path: 'media', only: [:create]
  end
  post '/projects/sync/:sf_object_id', to: 'projects#sync_with_sf'
  resources :project_media, only: [:show, :destroy]

  match '/home/autocomplete' => "home#autocomplete"
  match '/search' => 'home#wide_search', :as => :wide_search
  match '/autocomplete' => 'home#elastic_autocomplete'
  resources :students_setup, path: "/students/setup", only: [:index, :show, :update]
  get '/students_setup/project_sessions/:project' => 'students_setup#project_sessions'
  get '/projects_setup/application_deadline/:id' => 'projects_setup#application_deadline'

  resources :students
  post '/students/sync/:sf_object_id', to: 'students#sync_with_sf'
  post 'apply' => 'students#apply', :as => :apply

  resources :dashboards, only: [:index]
  resources :sessions
  get '/unique/:model/:attribute/:value' => 'uniqueness#validate', constraints: { value: /[^\/?]+/ }

  put "dashboards/update_login" => "dashboards#update_login"

  resources :organizations
  
  resources :donations, path: "/donations"
  get '/donate' => 'donations#new'
  get '/donate_to_student/:student_id' => 'donations#new', :as => :donate_to_student
  get '/renew_donation/:subscription_id' => 'donations#new', :as => :renew_donation
  get '/reserve_my_spot/:student_application_id' => 'donations#new', :as => :reserve_my_spot

  mount Sidekiq::Web, at: '/sidekiq'
  mount Refinery::Core::Engine, :at => '/'

  Refinery::Core::Engine.routes.draw do
    devise_scope :refinery_user do
      get "refinery/login", :to => "sessions#new", :as => :login
      get "refinery/logout", :to => "sessions#destroy", :as => :logout
      get "refinery/users/register" => 'users#new', :as => :new_signup
      post "refinery/users/register" => 'users#create', :as => :signup
    end

    devise_for :refinery_user, :class_name => 'Refinery::User',
               :path => "refinery/users",
               :controllers => { :registrations => 'refinery/users' },
               :skip => [:registrations],
               :path_names => { :sign_out => 'logout',
                                :sign_in => 'login',
                                :sign_up => 'register' }
  end
end

app/models/project.rb
# -*- coding: utf-8 -*-
class Project < ActiveRecord::Base
  extend Enumerize
  include SFRails::ActiveRecord
  include Formatter

  SF_PROJECT_APPLICATION_URL = "https://cs18.salesforce.com/services/apexrest/ProjectApplication"

  DENIED = "denied"
  APPROVED = "approved"
  IN_REVIEW = "in_review"
  COMPLETE = "complete"
  INCOMPLETE = "incomplete"

  salesforce "Project__c",
    [ :status, :agree_memo, :agree_to_transport, :challenges_description,
      :created_at, :culture_description, :description,
      :dining_location, :guidelines_description, :housing_description,
      :housing_type, :internet_distance, :location_city, :location_country,
      :location_description, :location_private, :location_state_or_province,
      :location_street_address, :location_type, :max_students,
      :min_stay_duration, :min_students, :name, :currency,
      :per_week_cost, :per_week_cost_final, :region, :related_fields_of_study, 
      :related_student_passions, :required_languages, :safety_level, 
      :student_educational_requirement, :team_mode, :transportation_available, 
      :typical_attire, :updated_at ]

  searchkick autocomplete: ['name']

  belongs_to :organization
  belongs_to :field_host
  has_many :project_media
  has_many :project_sessions
  has_many :student_applications, through: :project_sessions
  has_many :sessions, through: :project_sessions
  serialize :properties, ActiveRecord::Coders::Hstore

  delegate :references, to: :field_host

  hstore_accessor :properties, :min_stay_duration, :min_students, :max_students,
    :per_week_cost, :per_week_cost_final, :currency, :required_languages, :student_educational_requirement,
    :internet_distance, :location_type, :transportation_available, :location_description,
    :culture_description, :housing_type, :dining_location, :housing_description, :safety_level,
    :challenges_description, :typical_attire, :guidelines_description, :agree_memo, :agree_to_transport

  attr_accessible :name, :description, :team_mode, :min_stay_duration, :min_students, :max_students, :status,
    :per_week_cost, :per_week_cost_final, :currency, :required_languages, :related_student_passions, :related_fields_of_study,
    :student_educational_requirement, :location_street_address, :location_city, :location_state_or_province, :location_country, 
    :internet_distance, :location_private, :location_type, :transportation_available, :location_description, :culture_description, 
    :housing_type, :dining_location, :housing_description, :safety_level, :challenges_description, :typical_attire, 
    :guidelines_description, :agree_memo, :agree_to_transport, :field_host_attributes, :organization_attributes, 
    :region, :organization_id, :wizard_status, :project_sessions_attributes, :field_host_id, :created_at, :updated_at

  accepts_nested_attributes_for :field_host
  accepts_nested_attributes_for :organization
  accepts_nested_attributes_for :project_sessions, reject_if: :all_blank, allow_destroy: true

  enumerize :status, in: %w(incomplete complete in_review approved denied), I18n_scope: "enumerize.project.status"

  %w(dining_location internet_distance location_type housing_type safety_level region
    typical_attire student_educational_requirement).each do |f|
    enumerize f, in: I18n.t("enumerize.project.#{f}")

    # =================
    # TEMPORARY KLUDGE:
    # =================
    # Postgresql array/hstore serialization is interfering with ‘enumerize’.
    # Enumerize creates customer getters for its enumerated properties to return objects of type Enumerize::Value
    # instead of the raw value stored to the database. When object.value is accessed, enumerize returns an object
    # of type Enumerize::Value.
    #
    #
    # When combined with hstore serialization, the serialization "undoes" the getters defined by enumerize, so
    # object.value just returns the raw string saved to the database.
    # Since our getters no longer return an object of type Enumerize::Value, we do not have automatic access
    # to the translated value.
    #
    # The kludge below basically does what enumerize would do for us, and will work in the interim until someone
    # can get enumerize to play well with our hstores.
    #
    define_method "#{f}_text" do
      key = send(f)
      if key
        I18n.t("enumerize.project.#{f}." + key)
      else
        ""
      end
    end
  end

  %w(required_languages transportation_available).each do |f|
    enumerize f, in: I18n.t("enumerize.project." + f), multiple: true

    define_method "#{f}_with_deserialize" do
      value = send("#{f}_without_deserialize")
      value = JSON.parse(send("#{f}_without_deserialize")) if value && value.is_a?(String)
      return value # DO NOT remove this line. Must ensure value 
                   # is always returned regardless if "if" statement runs
    end
    alias_method_chain f, :deserialize
  end

  %w(related_fields_of_study related_student_passions).each do |f|
    enumerize f, in: I18n.t("enumerize.project." + f), multiple: true
  end

  # -- About You
  validates :field_host, :organization, :associated => true, :if => :complete_or_about_you?
 # before_save :relate_fieldhost_to_organization, :if => :complete_or_about_you?
  # -- The Project
  validates :name, :student_educational_requirement, :presence => true, :if => :complete_or_the_project?
  validates :name, uniqueness: true, :if => :complete_or_the_project?
  validates :team_mode, inclusion: {in: [true, false]}, :if => :complete_or_the_project?
  validates :min_students, :max_students, :per_week_cost, :numericality => true, :if => :complete_or_the_project?
  # -- Location
  validates :location_private, inclusion: {in: [true, false]}, :if => :complete_or_location?
  validates :location_street_address, :location_city, :location_state_or_province, :location_country, :region,
   :internet_distance, :location_description, :culture_description, :presence => true, :if => :complete_or_location?
  # -- Content
  validates :description, :housing_type, :dining_location, :housing_description, :safety_level, :challenges_description,
      :typical_attire, :guidelines_description, :presence => true, :if => :complete_or_content?
  # -- Agreement
  validates :agree_memo, :agree_to_transport, inclusion: { in: [true, 1, 'true', 'T', '1'], message: "You must agree the terms in order to continue" }, :if => :complete_or_agreement?


  scope :denied, where(status: DENIED)
  scope :approved, where(status: APPROVED)
  scope :in_review, where(status: IN_REVIEW)
  # unapproved = completed, but hasn't been approved yet.
  scope :unapproved, where("status = ? OR status = ?", COMPLETE, IN_REVIEW) 
  scope :incomplete, where("wizard_status != ?", COMPLETE)
  scope :complete, where(wizard_status: COMPLETE)
  
  scope :recent, order('created_at desc')
  scope :oldest, order('created_at asc')
  scope :by_name, order('name asc')


  # Returns all projects with at least one project session that has available spots.
  # 
  # Counts all approved applications and compare to the total available spots.
  # Returns projects where total available spots > approved applications.

  def self.available_seats
    joins(:project_sessions)
    .joins("
      LEFT OUTER JOIN student_applications 
      ON student_applications.project_session_id = project_sessions.id AND student_applications.status = 'reserved'    
     ")
    .having("(
      CAST(properties -> 'max_students' AS FLOAT) * COUNT(DISTINCT project_sessions.id)) > COUNT(student_applications.id)        
     ")
    .group("projects.id")
  end

  def self.top_ten(array_name)
    items = Project.connection.select_all(
      "select unnest(#{array_name.to_s}) as array_name, 
      count(*) from Projects where status = '#{Project::APPROVED}' 
      group by array_name order by count DESC limit 10")
    items.map{ |item| item["array_name"] }
  end

  def self.top_ten_student_passions
    top_ten(:related_student_passions)
  end

  def self.top_ten_fields_of_study
    top_ten(:related_fields_of_study)
  end

  def seats_left?
    (project_sessions.count * max_students) > reserved_applications.count
  end

  def agree_memo; properties["agree_memo"] == "1" ? true : false; end;
  def agree_to_transport; properties["agree_to_transport"] == "1" ? true : false; end;
  def per_week_cost_final; properties["per_week_cost_final"] == "1" ? true : false; end;

  def max_students
    properties["max_students"].to_i
  end

  def min_students
    properties["min_students"].to_i
  end

  def search_data
    as_json only: [:name, :description]
  end

  def set_to_complete
    return if status == APPROVED
    self.status = COMPLETE
  end

  def editable?
    self.status == COMPLETE || self.status == INCOMPLETE
  end

  def complete?
    wizard_status == 'complete'
  end

  def complete_or_about_you?
    wizard_status.include?('about_you') || complete?
  end

  def complete_or_the_project?
    wizard_status.include?('the_project') || complete?
  end

  def complete_or_location?
    wizard_status.include?('location') || complete?
  end

  def complete_or_content?
    wizard_status.include?('content') || complete?
  end

  def complete_or_agreement?
    wizard_status.include?('agreement') || complete?
  end

  def relate_fieldhost_to_organization
    self.field_host.organization_id = self.organization_id
  end

  def get_pretty_properties(properties, type)
    properties = [] if properties.nil?

    all_properties = I18n.t("enumerize.project." + type)
    pretty_properties = []
    properties.each do |property|
      pretty_properties << all_properties[property.to_sym]
    end

    pretty_properties.join(", ")
  end

  def full_address
    "#{location_street_address}, #{location_city},
    #{location_state_or_province}, #{location_country}"
  end

  # TODO: Partial validations with wizard steps
  # validates_presence_of :name, :description
  # validates_uniqueness_of :name

  #create/update object in SF
  def save_to_sf!

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_login!, :only => [:new, :create]
  before_filter :convert_to_datetime, :validate_home_search, :only => [:index]
  protect_from_forgery except: :sync_with_sf

  respond_to :html, :js

  def index
    projects = ProjectLoader.load_projects(params[:properties])
    @projects = projects.approved.ransack(params[:q])
    @total_projects = @projects.result.count
    @sessions = Session.order(:start_date)
    params[:view] ||= 'grid'
    params[:order] ||= 'name'
  end


  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    flash[:notice] = "Project was successfully created." if @project.save
    respond_with(@project) do |format|
      format.html { redirect_to projects_path }
    end
  end

  def edit
    authorize! :edit, Project.find(params[:id])
    session[:project_id] = params[:id]
    session[:editing_project] = true
    redirect_to projects_setup_path(:about_you)
  end

  def show
    @p = Project.find(params[:id])
    @o = Organization.find(@p.organization_id)
    @project_media = ProjectMedia.where(params[:project])
    @host = FieldHost.find(Project.find(params[:id]).field_host_id)
  end

  def sync_with_sf
    begin
      sf_project = Project.sf.find_by_id(params[:sf_object_id])
      sf_field_host = FieldHost.sf.find_by_id(sf_project.FieldHost__c)
      sf_organization = Organization.sf.find_by_id(sf_project.Organization__c)
      ActiveRecord::Base.transaction do
        sf_project.save_to_rails!
        sf_field_host.save_to_rails! if sf_field_host
        sf_organization.save_to_rails! if sf_organization
      end
      render json: sf_project
    rescue => e
      Rails.logger.error "Error updating Project from Salesforce: #{e.message}"
      render json: { error: e.message }, status: 400
    end
  end

  private

  def validate_home_search
    return if params[:related_field_of_study].blank?
    field = params[:related_field_of_study]

    params[:properties] = {}
    params[:properties][:related_fields_of_study] = current_fields_of_study.invert[field].to_s.split
    @field_of_study = params[:properties][:related_fields_of_study]
    @name_or_address = params[:q][:name_or_address_cont]
  end


  def convert_to_datetime
    return unless params[:q].present?
    params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day if params[:q][:created_at_gt].present?
    params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day if params[:q][:created_at_lt].present?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def pretty_date(date)
    date.to_formatted_s(:long_ordinal)
  end

  def wizard_step(label, index, url, current_step)
    content_tag(:li) do
      raw(
        if index == current_step
          link_to(url) do
            raw(label + content_tag(:span, "", class: "circle"))
          end
        elsif index < current_step
          link_to(url) do
            raw(label + content_tag(:span, "", class: "small-circle"))
          end
        else
          label + content_tag(:span, "", class: "small-circle")
        end
      )
    end
  end

  def fields_of_study
    current_fields_of_study.invert
  end

  def student_passions
    current_student_passions.invert
  end
end

app/views/projects/_button_group.html.haml
.button-group
  = button_link_to t(:grid), projects_path(view: 'grid', order: params[:order], q: params[:q], properties: params[:properties]), :grey, id: 'grid_button', class: view_active?('grid') + ' entypo-grid', remote: true
  = button_link_to t(:list), projects_path(view: 'list', order: params[:order], q: params[:q], properties: params[:properties]), :grey, id: 'list_button', class: view_active?('list') + ' entypo-list', remote: true

app/views/projects/_no_projects_available.html.haml
%h2.not-available= t(:no_projects_available)
.center
	= link_to t(:browse_all_projects), projects_path, id: "browse_all_projects", class: "button button-orange", remote: true

app/views/projects/_project_media_display.html.haml
.media
  %img{:src => @project_media.image.url(:thumb)}

app/views/projects/_projects_grid.html.haml
- projects.each do |p|
  .project.c4.project-result{'data' => {'project' => p.id}}
    = image_tag p.project_media.first.image_url(:medium) unless p.project_media.empty?
    .project-description
      %h3= p.name
      %p= truncate(p.description, :length => 50, :omission => ' ...')
      %p= p.region_text
      %p.team_mode= p.team_mode ? "team" : "individual"
      / %p= p.get_pretty_properties(p.related_fields_of_study, "related_fields_of_study")
      / %p= p.get_pretty_properties(p.related_student_passions, "related_student_passions")

app/views/projects/_projects_grid.html.slim
- projects.each do |p|
  .project.c4
    h3= p.name
    p= p.description
    - if p.start_date || p.end_date
      p.date-bar

        - if p.start_date
          |  Start:
          = p.start_date

        - if p.end_date
          |  - End:
          = p.end_date

app/views/projects/_projects_list.html.haml
%table.table
  %thead.table-head
    %tr
      %th= t(:name)
      %th= t(:description)
      %th= t(:region)
      %th= t(:team)
      %th= t(:student_fields)
      %th= t(:student_passions)

  %tbody.table-body
    - projects.each do |p|
      %tr.project-result{'data' => {'project' => p.id}}
        %td= p.name
        %td= truncate(p.description, :length => 50, :omission => ' ...')
        %td= p.region_text
        %td= p.team_mode ? "Team" : "Individual"
        %td= p.get_pretty_properties(p.related_fields_of_study, "related_fields_of_study")
        %td= p.get_pretty_properties(p.related_student_passions, "related_student_passions")

app/views/projects/_projects_list.html.slim
table.table
  thead.table-head
    tr
      th Name
      th Description
      th Start
      th End

  tbody.table-body
    - projects.each do |p|
      tr
        td= p.name
        td= p.description
        td= p.start_date
        td= p.end_date

app/views/projects/_projects_map.html.slim
h2.not-available Map View Not Available

app/views/projects/_sort_links.html.haml
.button-group
	= button_link_to t(:a_z), projects_path(order: 'name', view: params[:view], properties: params[:properties], q: params[:q]), remote: true
	= button_link_to t(:recent), projects_path(order: 'created_at asc', view: params[:view], properties: params[:properties], q: params[:q]), remote: true
	= button_link_to t(:oldest), projects_path(order: 'created_at desc', view: params[:view], properties: params[:properties], q: params[:q]), remote: true

app/views/projects/index.html.haml
.container
  .explore
    .c6.alpha
      / %h3= t(:explore_ipo_connection_projects)
      .total-projects= "#{@total_projects.to_s} #{t(:total_projects)}"

    .c6.omega.options
      / %h4.explore-by= t(:explore_by)
      = render "sort_links"
      = render "button_group"

 
  = search_form_for @projects, builder: SimpleForm::FormBuilder, remote: true do |f|
    = hidden_field_tag :view, params[:view]

    .c12
      .c9= f.text_field :name_or_address_cont, size: 15, placeholder: t(:project_search_placeholder), value: @name_or_address
      .filter.c3.omega
        %div
          %h3= "Advanced Filters"
        %div#filter-details
          %label= t(:project_mode)
          %label.checkbox
            = t(:team)
            = f.check_box :team_mode_true, { :data => {:toggle => "checkbox"} }
          %label.checkbox
            = t(:individual)
            = f.check_box :team_mode_false, { :data => {:toggle => "checkbox"} }
          %label= t(:session_timeframe)
          = f.collection_select :sessions_id_in, @sessions, :id, :select_label, {}, include_blank: true, multiple: true

          / .include
          %label= t(:fields_of_study)
          = select_tag "properties[related_fields_of_study]", options_for_select(fields_of_study, @field_of_study), include_blank: true , multiple: true 

          %h4= t(:filter_by_passion)
          .clr

          %div.student_passions
            - student_passions.each do |key, value|
              %label.checkbox
                = check_box_tag "properties[related_student_passions][]", value, false, :data => {:toggle => "checkbox"}
                = key
      
      .hide
        = f.submit t(:search), class: "button button-orange"

      .c9.alpha.search-results
        - if @projects.result.empty?
          = render "no_projects_available"
        - else
          #related_projects
            = render "projects_#{params[:view]}", projects: @projects.result.order("#{params[:order]}")





:javascript
  $("#q_created_at_gt").datepicker({ dateFormat: "yy/mm/dd" });
  $("#q_created_at_lt").datepicker({ dateFormat: "yy/mm/dd" });
  $(document).on("click", ".project-result", (function() {
    $(location).attr('href', "/projects/" + $(this).data('project'));
  }));

  $("input").change(function() {
    $("form.project_search input[type='submit']").submit();
  });
//    $(location).attr('href', "/projects/" + $(this).data('project'));     alert( "Goodbye!" ); // jQuery 1.4.3+

app/views/projects/index.html.slim
article.box.container
  .explore
    .c8
      h3 Explore IPO Connection Projects
      = button_link_to 'Create New Project', new_project_path, :blue, class: 'new-project'

    .options
      span.explore-by Explore By:
      .button-group
        = button_link_to 'Map',  projects_path(view: 'map'),  :grey, class: view_active?('map')
        = button_link_to 'Grid', projects_path(view: 'grid'), :grey, class: view_active?('grid')
        = button_link_to 'List', projects_path(view: 'list'), :grey, class: view_active?('list')

  = search_form_for @q do |f|
    = hidden_field_tag :view, params[:view]
    .filter
      .sort
        span.explore-by Sort:
        .button-group
          = sort_button 'A-Z', 'name asc'
          = sort_button 'Recent', 'created_at desc'
          = sort_button 'Oldest', 'created_at asc'


      .include
        span Filter:
        = dropdown 'Any #' do
          = dropdown_btn '1-10'
          = dropdown_btn '10-40'
          = dropdown_btn '40+'

        = dropdown 'Weeks' do
          = dropdown_btn 'Days'
          = dropdown_btn 'Weeks'
          = dropdown_btn 'Months'
          = dropdown_btn 'Years'

        span.interests Passion Interests:
        = dropdown 'All' do
          = dropdown_btn '??'
          = dropdown_btn '??'

      .search
        = f.text_field :name_cont

  = render "projects_#{params[:view]}", projects: @projects

app/views/projects/index.js.erb
$("#option_buttons").html("<%= escape_javascript(render 'button_group') %>");
$("#sort_links").html("<%= escape_javascript(render 'sort_links') %>");
$(".total-projects").html('<%= "#{@total_projects.to_s} #{t(:total_projects)}" %>')
<% if @projects.result.empty? %>
	$("#related_projects").html("<%= escape_javascript(render 'no_projects_available') %>")
	$('#browse_all_projects').on('click', function() {
    	$("#project_search input[type='text']").val('');
    	$("#project_search input[type='checkbox']").removeAttr('checked');
      $("#project_search .checkbox").removeClass('checked');
    	$("#properties_related_fields_of_study").select2('data', null)
    });
<% else
   	view = params[:view] 
  	projects = "projects_#{view}"
  	order = params[:order]  %>
	$("#related_projects").html("<%= escape_javascript(render projects, projects: @projects.result.order(order)) %>");
  $("#view").val("<%=view%>");
<% end %>

app/views/projects/new.html.slim
article.box.container
  #new-project
    h2.w-seperator Create a New Project

    = simple_form_for @project, validate: true do |f|
      = f.input :name
      = f.input :description
      = f.input :start_date, as: :date_picker
      = f.input :end_date, as: :date_picker

      = f.submit class: 'button button-green'
      span.or OR
      = button_link_to 'Back to Projects', projects_path, :blue

app/views/projects/show.html.haml
.container.topbuffer
  .primary
    %label= t(:project_name)
    %h1= @p.name

    .box.bxslider
      - @p.project_media.each do |m|
        %li
          %img.imagesize{:src => m.image.url}

    .box#bx-pager
      - @p.project_media.each_with_index do |m, i|
        %a{:href => "#", :data => {:slide => {:index => i}}}
          %img{:src => m.image.url(:thumb)}

    %h3= t(:sponsoring_organization)
    %p= @o.name
    %p= @o.organization_type

    %h3 Overview

    %label= t(:description)
    %p= @p.description

    #callout-overview
      .third
        %label= t(:fields_of_study)
        %p= @p.get_pretty_properties(@p.related_fields_of_study, "related_fields_of_study")

      .third
        %label= t(:student_passions)
        %p= @p.get_pretty_properties(@p.related_student_passions, "related_student_passions")

      .third
        %label= t(:needed_lanaguages)
        %p= @p.get_pretty_properties(@p.required_languages, "required_languages")

      %label= t(:project_sessions)
      %table
        %thead
          %tr
            %th= t(:title)
            %th= t(:start_date)
            %th= t(:end_date)
            %th= t(:application_deadline)
            %th= t(:seats_left)
        %tbody
          - @p.project_sessions.each do |s|
            %tr
              %td= s.title
              %td= s.start_date.to_formatted_s(:rfc822)
              %td= s.end_date.to_formatted_s(:rfc822)
              %td= s.application_deadline.to_formatted_s(:rfc822)
              %td= s.seats_left

    %h3 Internship Location & Culture

    %label= t(:culture_description)
    %p= @p.culture_description
    %label= t(:location_description)
    %p= @p.location_description
    %label= t(:challenges_description)
    %p= @p.challenges_description
    %label= t(:guidelines_description)
    %p= @p.guidelines_description
    %label= t(:housing)
    %p= @p.housing_description

    %h3 Project Staff

    %label= @host.organization
    %p #{@host.first_name} , #{@host.role_title}
    %p= @host.get_pretty_properties(@host.experience_with_ywam, "experience_with_ywam")

  .secondary
    .info.rounded= link_to "Back to Projects", projects_path, 'class' => "clr"

    .info.rounded
      %h3 Get Started
      - if can? :apply, @p
        = link_to "Apply", students_setup_index_path(project_id: @p), class: "button button-orange entypo-apply"
      - else
        %h2.grey= t(:sorry_project_full)

    .info.rounded
      %h3 Share
      .fb-share-button{:data => {:type => "button"}}

    .info.rounded
      %h3 Project Details

      %label= t(:team_mode)
      %p= @p.team_mode ? "Team" : "Individual"

      %label= t(:student_educational_requirement)
      %p= @p.student_educational_requirement_text

      %label= t(:housing)
      %p= @p.housing_type_text

      %label= t(:typical_attire)
      %p= @p.typical_attire_text

      %label= t(:student_dining_location)
      %p= @p.dining_location_text

      %label= t(:per_week_cost)
      %p= @p.per_week_cost


    .info.rounded
      %h3 Location

      %label= t(:location_and_region)
      %p= @p.location_type_text

      %label= t(:area_transportation)
      %p= @p.get_pretty_properties(@p.transportation_available,"transportation_available")

      %label= t(:safety_level)
      %p= @p.safety_level_text


      %label= t(:internet_distance)
      %p= @p.internet_distance_text